---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
  labels:
    app: my-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: my-flask-app-container
        image: us-central1-docker.pkg.dev/anderson-sre-465021/sre-training-repo/my-flask-app:v1.14
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://trace.googleapis.com:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "false"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: GOOGLE_CLOUD_PROJECT
          value: "anderson-sre-465021"
        - name: OTEL_LOG_LEVEL
          value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  labels:
    app: my-flask-app
spec:
  selector:
    app: my-flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080